const record=document.getElementById('record'),status=document.getElementById('status'),note=document.getElementById('note'),freq=document.getElementById('freq'),melody=document.getElementById('melody'),clear=document.getElementById('clear'),play=document.getElementById('play');
const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];let ctx,analyser,stream,source,recording=false,seq=[],lastMidi=null,lastAdd=0;
function midiToFreq(m){return 440*Math.pow(2,(m-69)/12)} function label(m){return names[((m%12)+12)%12]+(Math.floor(m/12)-1)}
function detect(b,sr){let rms=Math.sqrt(b.reduce((x,v)=>x+v*v,0)/b.length);if(rms<.012)return null;let best=-1,bc=0,min=Math.floor(sr/1000),max=Math.min(Math.floor(sr/70),b.length-1);for(let lag=min;lag<=max;lag++){let a=0,x=0,y=0;for(let i=0;i<b.length-lag;i++){a+=b[i]*b[i+lag];x+=b[i]*b[i];y+=b[i+lag]*b[i+lag]}let c=a/Math.sqrt((x*y)||1);if(c>bc){bc=c;best=lag}}if(best<0||bc<.55)return null;return{f:sr/best,c:bc}}
function loop(){if(!recording)return;let b=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(b);let r=detect(b,ctx.sampleRate);if(r){let m=Math.round(69+12*Math.log2(r.f/440));note.textContent=label(m);freq.textContent=r.f.toFixed(1)+' Hz';let now=performance.now();if(m!==lastMidi||now-lastAdd>450){seq.push({m,t:now});lastMidi=m;lastAdd=now;render()}}requestAnimationFrame(loop)}
function render(){melody.innerHTML=seq.length?seq.map(x=>`<span class="pill">${label(x.m)}</span>`).join(''):'Your detected notes will appear here.';play.disabled=!seq.length}
record.onclick=async()=>{if(recording){recording=false;stream?.getTracks().forEach(t=>t.stop());source?.disconnect();ctx?.close();record.classList.remove('recording');record.textContent='Start Humming';status.textContent=seq.length?'Melody captured':'Ready';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,autoGainControl:false,noiseSuppression:false}});ctx=new(window.AudioContext||window.webkitAudioContext)();analyser=ctx.createAnalyser();analyser.fftSize=2048;source=ctx.createMediaStreamSource(stream);source.connect(analyser);recording=true;record.classList.add('recording');record.textContent='Stop Recording';status.textContent='Listening…';loop()}catch(e){status.textContent='Microphone permission unavailable.'}};
clear.onclick=()=>{seq=[];lastMidi=null;render();note.textContent='—';freq.textContent='—';status.textContent='Ready'};
play.onclick=async()=>{let c=new(window.AudioContext||window.webkitAudioContext)(),start=c.currentTime+.05,step=.42;seq.forEach((x,i)=>{let o=c.createOscillator(),g=c.createGain(),t=start+i*step;o.type='sine';o.frequency.value=midiToFreq(x.m);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.16,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+step*.9);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+step)});setTimeout(()=>c.close(),seq.length*step*1000+300)};
render();
